[package]
name = "audiosplit_core"
version = "0.1.0"
edition = "2021"
authors = ["AudioSplit Contributors"]
license = "MIT"

[dependencies]
symphonia = { version = "0.5" }
thiserror = "1"
log = "0.4"

[dev-dependencies]
tempfile = "3"
